// Mocks generated by Mockito 5.4.6 from annotations
// in Tap_Go/test/clients_widgets_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i8;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i9;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i11;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i14;
import 'package:flutter_local_notifications/src/platform_specifics/ios/enums.dart'
    as _i13;
import 'package:flutter_local_notifications/src/types.dart' as _i15;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:Tap_Go/services/offers_service.dart' as _i7;
import 'package:Tap_Go/services/parking_service.dart' as _i3;
import 'package:Tap_Go/services/queue_service.dart' as _i2;
import 'package:timezone/timezone.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeQueueMetrics_0 extends _i1.SmartFake implements _i2.QueueMetrics {
  _FakeQueueMetrics_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTicketCalculation_1 extends _i1.SmartFake
    implements _i3.TicketCalculation {
  _FakeTicketCalculation_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_2<T1 extends Object?> extends _i1.SmartFake
    implements _i4.DocumentReference<T1> {
  _FakeDocumentReference_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSnapshotMetadata_3 extends _i1.SmartFake
    implements _i4.SnapshotMetadata {
  _FakeSnapshotMetadata_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueueService extends _i1.Mock implements _i2.QueueService {
  MockQueueService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> getOwnerShopId() =>
      (super.noSuchMethod(
            Invocation.method(#getOwnerShopId, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getOwnerShopId, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> initializeQueue(String? shopId) =>
      (super.noSuchMethod(
            Invocation.method(#initializeQueue, [shopId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i2.AdminQueueStats> getAdminStatsStream(String? shopId) =>
      (super.noSuchMethod(
            Invocation.method(#getAdminStatsStream, [shopId]),
            returnValue: _i5.Stream<_i2.AdminQueueStats>.empty(),
          )
          as _i5.Stream<_i2.AdminQueueStats>);

  @override
  _i5.Future<void> advanceQueueSmart(String? shopId) =>
      (super.noSuchMethod(
            Invocation.method(#advanceQueueSmart, [shopId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markCurrentAsNoShow(String? shopId) =>
      (super.noSuchMethod(
            Invocation.method(#markCurrentAsNoShow, [shopId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i4.DocumentSnapshot<Object?>> getQueueStream(String? queueId) =>
      (super.noSuchMethod(
            Invocation.method(#getQueueStream, [queueId]),
            returnValue: _i5.Stream<_i4.DocumentSnapshot<Object?>>.empty(),
          )
          as _i5.Stream<_i4.DocumentSnapshot<Object?>>);

  @override
  _i5.Future<int> joinQueue(String? queueId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#joinQueue, [queueId, userId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i2.QueueMetrics calculateMetrics(
    _i4.DocumentSnapshot<Object?>? doc,
    int? myTicketNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateMetrics, [doc, myTicketNumber]),
            returnValue: _FakeQueueMetrics_0(
              this,
              Invocation.method(#calculateMetrics, [doc, myTicketNumber]),
            ),
          )
          as _i2.QueueMetrics);
}

/// A class which mocks [OffersService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffersService extends _i1.Mock implements _i7.OffersService {
  MockOffersService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get collection =>
      (super.noSuchMethod(
            Invocation.getter(#collection),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#collection),
            ),
          )
          as String);

  @override
  String cleanNfcPayload(String? rawText) =>
      (super.noSuchMethod(
            Invocation.method(#cleanNfcPayload, [rawText]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#cleanNfcPayload, [rawText]),
            ),
          )
          as String);

  @override
  String extractShopId(String? rawCode) =>
      (super.noSuchMethod(
            Invocation.method(#extractShopId, [rawCode]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#extractShopId, [rawCode]),
            ),
          )
          as String);

  @override
  _i5.Stream<List<_i7.OfferModel>> getOffersByShop(String? shopId) =>
      (super.noSuchMethod(
            Invocation.method(#getOffersByShop, [shopId]),
            returnValue: _i5.Stream<List<_i7.OfferModel>>.empty(),
          )
          as _i5.Stream<List<_i7.OfferModel>>);

  @override
  _i5.Future<String> getAdminShopId() =>
      (super.noSuchMethod(
            Invocation.method(#getAdminShopId, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getAdminShopId, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Stream<List<_i7.OfferModel>> getAdminOffersStream(String? shopId) =>
      (super.noSuchMethod(
            Invocation.method(#getAdminOffersStream, [shopId]),
            returnValue: _i5.Stream<List<_i7.OfferModel>>.empty(),
          )
          as _i5.Stream<List<_i7.OfferModel>>);

  @override
  _i5.Future<void> createOffer({
    required String? shopId,
    required String? title,
    required String? code,
    required bool? isActive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOffer, [], {
              #shopId: shopId,
              #title: title,
              #code: code,
              #isActive: isActive,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleOfferStatus(String? offerId, bool? newStatus) =>
      (super.noSuchMethod(
            Invocation.method(#toggleOfferStatus, [offerId, newStatus]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteOffer(String? offerId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOffer, [offerId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ParkingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockParkingService extends _i1.Mock implements _i3.ParkingService {
  MockParkingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get collection =>
      (super.noSuchMethod(
            Invocation.getter(#collection),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#collection),
            ),
          )
          as String);

  @override
  String cleanNfcPayload(String? rawText) =>
      (super.noSuchMethod(
            Invocation.method(#cleanNfcPayload, [rawText]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#cleanNfcPayload, [rawText]),
            ),
          )
          as String);

  @override
  String validateAndExtractShopId(String? rawCode) =>
      (super.noSuchMethod(
            Invocation.method(#validateAndExtractShopId, [rawCode]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#validateAndExtractShopId, [rawCode]),
            ),
          )
          as String);

  @override
  _i5.Future<String?> findActiveTicketId() =>
      (super.noSuchMethod(
            Invocation.method(#findActiveTicketId, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Stream<_i3.ParkingTicket> getTicketStream(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#getTicketStream, [ticketId]),
            returnValue: _i5.Stream<_i3.ParkingTicket>.empty(),
          )
          as _i5.Stream<_i3.ParkingTicket>);

  @override
  _i5.Future<String> checkIn(String? rawCode) =>
      (super.noSuchMethod(
            Invocation.method(#checkIn, [rawCode]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#checkIn, [rawCode]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> checkOut(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#checkOut, [ticketId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.TicketCalculation> verifyAndCalculateTicket(
    String? ticketId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAndCalculateTicket, [ticketId]),
            returnValue: _i5.Future<_i3.TicketCalculation>.value(
              _FakeTicketCalculation_1(
                this,
                Invocation.method(#verifyAndCalculateTicket, [ticketId]),
              ),
            ),
          )
          as _i5.Future<_i3.TicketCalculation>);

  @override
  _i5.Future<void> processPayment(String? ticketId, double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#processPayment, [ticketId, amount]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [DocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i4.DocumentSnapshot<T> {
  MockDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i4.DocumentReference<T> get reference =>
      (super.noSuchMethod(
            Invocation.getter(#reference),
            returnValue: _FakeDocumentReference_2<T>(
              this,
              Invocation.getter(#reference),
            ),
          )
          as _i4.DocumentReference<T>);

  @override
  _i4.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_3(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i4.SnapshotMetadata);

  @override
  bool get exists =>
      (super.noSuchMethod(Invocation.getter(#exists), returnValue: false)
          as bool);

  @override
  dynamic get(Object? field) =>
      super.noSuchMethod(Invocation.method(#get, [field]));

  @override
  dynamic operator [](Object? field) =>
      super.noSuchMethod(Invocation.method(#[], [field]));
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i8.FlutterLocalNotificationsPlugin {
  MockFlutterLocalNotificationsPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool?> initialize(
    _i9.InitializationSettings? initializationSettings, {
    _i10.DidReceiveNotificationResponseCallback?
    onDidReceiveNotificationResponse,
    _i10.DidReceiveBackgroundNotificationResponseCallback?
    onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initialize,
              [initializationSettings],
              {
                #onDidReceiveNotificationResponse:
                    onDidReceiveNotificationResponse,
                #onDidReceiveBackgroundNotificationResponse:
                    onDidReceiveBackgroundNotificationResponse,
              },
            ),
            returnValue: _i5.Future<bool?>.value(),
          )
          as _i5.Future<bool?>);

  @override
  _i5.Future<_i10.NotificationAppLaunchDetails?>
  getNotificationAppLaunchDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationAppLaunchDetails, []),
            returnValue: _i5.Future<_i10.NotificationAppLaunchDetails?>.value(),
          )
          as _i5.Future<_i10.NotificationAppLaunchDetails?>);

  @override
  _i5.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i11.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #show,
              [id, title, body, notificationDetails],
              {#payload: payload},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancel(int? id, {String? tag}) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [id], {#tag: tag}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i12.TZDateTime? scheduledDate,
    _i11.NotificationDetails? notificationDetails, {
    required _i13.UILocalNotificationDateInterpretation?
    uiLocalNotificationDateInterpretation,
    required _i14.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i15.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #zonedSchedule,
              [id, title, body, scheduledDate, notificationDetails],
              {
                #uiLocalNotificationDateInterpretation:
                    uiLocalNotificationDateInterpretation,
                #androidScheduleMode: androidScheduleMode,
                #payload: payload,
                #matchDateTimeComponents: matchDateTimeComponents,
              },
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i10.RepeatInterval? repeatInterval,
    _i11.NotificationDetails? notificationDetails, {
    required _i14.AndroidScheduleMode? androidScheduleMode,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShow,
              [id, title, body, repeatInterval, notificationDetails],
              {#androidScheduleMode: androidScheduleMode, #payload: payload},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval,
    _i11.NotificationDetails? notificationDetails, {
    _i14.AndroidScheduleMode? androidScheduleMode =
        _i14.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShowWithDuration,
              [id, title, body, repeatDurationInterval, notificationDetails],
              {#androidScheduleMode: androidScheduleMode, #payload: payload},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i10.PendingNotificationRequest>>
  pendingNotificationRequests() =>
      (super.noSuchMethod(
            Invocation.method(#pendingNotificationRequests, []),
            returnValue:
                _i5.Future<List<_i10.PendingNotificationRequest>>.value(
                  <_i10.PendingNotificationRequest>[],
                ),
          )
          as _i5.Future<List<_i10.PendingNotificationRequest>>);

  @override
  _i5.Future<List<_i10.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNotifications, []),
            returnValue: _i5.Future<List<_i10.ActiveNotification>>.value(
              <_i10.ActiveNotification>[],
            ),
          )
          as _i5.Future<List<_i10.ActiveNotification>>);
}
