// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDybI3b_otDLr1qBkqzbvIrrD2oW8mUzhQ',
    appId: '1:320679082222:web:8692850df100c2058d5bff',
    messagingSenderId: '320679082222',
    projectId: 'colas-virtuales',
    authDomain: 'colas-virtuales.firebaseapp.com',
    storageBucket: 'colas-virtuales.firebasestorage.app',
    measurementId: 'G-EHPLV060NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6xdIDkRXLVGbcq2CTaluJIZ-fWmlyV8s',
    appId: '1:320679082222:android:f62515901221c1cd8d5bff',
    messagingSenderId: '320679082222',
    projectId: 'colas-virtuales',
    storageBucket: 'colas-virtuales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAirPPyAzF06LCQoWG_b-XvUb8awbP52f4',
    appId: '1:320679082222:ios:20b94863d3306e328d5bff',
    messagingSenderId: '320679082222',
    projectId: 'colas-virtuales',
    storageBucket: 'colas-virtuales.firebasestorage.app',
    iosBundleId: 'com.example.colasVirtuales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAirPPyAzF06LCQoWG_b-XvUb8awbP52f4',
    appId: '1:320679082222:ios:20b94863d3306e328d5bff',
    messagingSenderId: '320679082222',
    projectId: 'colas-virtuales',
    storageBucket: 'colas-virtuales.firebasestorage.app',
    iosBundleId: 'com.example.colasVirtuales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDybI3b_otDLr1qBkqzbvIrrD2oW8mUzhQ',
    appId: '1:320679082222:web:6be985389d0e72148d5bff',
    messagingSenderId: '320679082222',
    projectId: 'colas-virtuales',
    authDomain: 'colas-virtuales.firebaseapp.com',
    storageBucket: 'colas-virtuales.firebasestorage.app',
    measurementId: 'G-MJJ2F8LZ59',
  );
}
